### ISSUE TITLE
Relative URI with spaces is not supported

### ISSUE THREAD

**Issue by sormuras** [TNG/ArchUnit#103]
Using `ClassFileImporter.importLocations` may yield an `URISyntaxException` when the name of a `JarEntry` contains space characters. Kotlin entity names may contain spaces:

`fun "assertAll with collection of functions that throw AssertionErrors"`

https://github.com/junit-team/junit5/blob/98eaf5d436e8d3db036efbc3be07acafafe413a8/junit-jupiter-engine/src/test/kotlin/org/junit/jupiter/api/KotlinAssertionsTests.kt#L71

```
Illegal character in opaque part at index 173: jar:file:/R:/dev/github/junit-team/junit5/junit-jupiter-engine/build/libs/junit-jupiter-engine-5.3.0-SNAPSHOT-test.jar!/org/junit/jupiter/api/KotlinAssertionsTests$assertAll with collection of functions that throw AssertionErrors$$inlined$assertThrows$1.class

at java.net.URI$Parser.fail(URI.java:2915)
at java.net.URI$Parser.checkChars(URI.java:3086)
at java.net.URI$Parser.parse(URI.java:3122)
at java.net.URI.<init>(URI.java:600)
at java.net.URI.create(URI.java:881)
at com.tngtech.archunit.core.importer.Location.append(Location.java:111)
at com.tngtech.archunit.core.importer.ClassFileSource$FromJar$ClassFileInJar.makeJarUri(ClassFileSource.java:167)
at com.tngtech.archunit.core.importer.ClassFileSource$FromJar$ClassFileInJar.<init>(ClassFileSource.java:163)
at com.tngtech.archunit.core.importer.ClassFileSource$FromJar$ClassFileInJar.<init>(ClassFileSource.java:155)
at com.tngtech.archunit.core.importer.ClassFileSource$FromJar$2.apply(ClassFileSource.java:122)
at com.tngtech.archunit.core.importer.ClassFileSource$FromJar$2.apply(ClassFileSource.java:119)
at com.tngtech.archunit.thirdparty.com.google.common.collect.Iterators$7.transform(Iterators.java:750)
at com.tngtech.archunit.thirdparty.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
at com.tngtech.archunit.thirdparty.com.google.common.collect.Iterators$6.computeNext(Iterators.java:616)
at com.tngtech.archunit.thirdparty.com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
at com.tngtech.archunit.thirdparty.com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
at com.tngtech.archunit.thirdparty.com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
at com.tngtech.archunit.thirdparty.com.google.common.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:47)
at com.tngtech.archunit.core.importer.ClassFileProcessor.process(ClassFileProcessor.java:51)
at com.tngtech.archunit.core.importer.ClassFileImporter.importLocations(ClassFileImporter.java:317)
at com.tngtech.archunit.junit.ClassCache$CacheClassFileImporter.importClasses(ClassCache.java:121)
at com.tngtech.archunit.junit.ClassCache$LazyJavaClasses.initialize(ClassCache.java:113)
at com.tngtech.archunit.junit.ClassCache$LazyJavaClasses.get(ClassCache.java:102)
at com.tngtech.archunit.junit.ClassCache.getClassesToAnalyzeFor(ClassCache.java:79)
at com.tngtech.archunit.junit.ArchUnitTestDescriptor.lambda$createChildren$1(ArchUnitTestDescriptor.java:82)
at com.tngtech.archunit.thirdparty.com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120)
at com.tngtech.archunit.junit.ArchUnitTestDescriptor$ArchUnitMethodDescriptor.execute(ArchUnitTestDescriptor.java:191)
at com.tngtech.archunit.junit.ArchUnitTestDescriptor$ArchUnitMethodDescriptor.execute(ArchUnitTestDescriptor.java:164)
...
```
Find the complete stacktrace here: https://scans.gradle.com/s/bdtjtzjxcirba/tests/ikpytbbcbornu-uwk356ykxf3uk?openStackTraces=WzFd

Encode the URI part with `URLEncoder`?

**Comment by codecholeric** [comment]
Oh man, URIs my old friends *sigh\* But thanks for reporting this :wink: 
I'll get right on it and release a bug fix.

**Comment by sormuras** [comment]
While you're at it: could `JavaClasses` get a `int size()` method returning the number of entries stored in the map?

After using `ClassFileImporter#import...` methods, I'd like to make assumptions on the number of mapped classes.

**Comment by sormuras** [comment]
> K, you got it 😉

And used it.

Let's see how it works out: https://github.com/junit-team/junit5/commit/5a44da8c6145611057923a8ae46df540c566fc04

Locally, all checks are green.

**Comment by codecholeric** [comment]
Yo, just give me a thumbs up if it seems good to release for you.

**Comment by sormuras** [comment]
👍 https://travis-ci.org/junit-team/junit5/jobs/418147668

**Comment by codecholeric** [comment]
Okay, I've released it to Maven Central. Will prolly take a couple of hours to get through.

**Comment by sormuras** [comment]
Worked flawlessly after some minutes. Thanks for the quick fix and release.

**Comment by codecholeric** [comment]
Glad it works now :smiley: Guess the sync that takes so long is just the sync to search.maven.org...
