### ISSUE TITLE
ArchUnit dependency breaks EJB Unit Tests

### ISSUE THREAD

**Issue by glatzg** [TNG/ArchUnit#137]
In our project we test EJB instances via TestNG and OpenEJB. Once I introduce the core ArchUnit dependency in Version 0.9.3 as per below

```
		<dependency>
			<groupId>com.tngtech.archunit</groupId>
			<artifactId>archunit</artifactId>
			<scope>test</scope>
		</dependency>
```

this breaks the EJB instance tests, with the following error message:

```
FATAL - OpenEJB has encountered a fatal error and cannot be started: Assembler failed to build the container system.
org.apache.openejb.OpenEJBException: java.lang.IllegalArgumentException: null
	at org.apache.openejb.assembler.classic.Assembler.build(Assembler.java:452)
	at org.apache.openejb.OpenEJB$Instance.<init>(OpenEJB.java:150)
	at org.apache.openejb.OpenEJB$Instance.<init>(OpenEJB.java:67)
	at org.apache.openejb.OpenEJB.init(OpenEJB.java:298)
	at org.apache.openejb.OpenEJB.init(OpenEJB.java:278)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.openejb.loader.OpenEJBInstance.init(OpenEJBInstance.java:36)
	at org.apache.openejb.core.LocalInitialContextFactory.init(LocalInitialContextFactory.java:98)
	at org.apache.openejb.core.LocalInitialContextFactory.init(LocalInitialContextFactory.java:62)
	at org.apache.openejb.core.LocalInitialContextFactory.getInitialContext(LocalInitialContextFactory.java:46)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.init(InitialContext.java:244)
	at javax.naming.InitialContext.<init>(InitialContext.java:216)
	at insure.general.claims.biomics.test.util.MicrocontainerTester.doSetUp(MicrocontainerTester.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:166)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:224)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.IllegalArgumentException
	at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
	at org.apache.openejb.util.AnnotationFinder.readClassDef(AnnotationFinder.java:299)
	at org.apache.openejb.util.AnnotationFinder.find(AnnotationFinder.java:164)
	at org.apache.openejb.config.DeploymentLoader.checkAnnotations(DeploymentLoader.java:2008)
	at org.apache.openejb.config.DeploymentLoader.discoverModuleType(DeploymentLoader.java:1891)
	at org.apache.openejb.config.DeploymentsResolver.processUrls(DeploymentsResolver.java:389)
	at org.apache.openejb.config.DeploymentsResolver.loadFromClasspath(DeploymentsResolver.java:302)
	at org.apache.openejb.config.ConfigurationFactory.getModulesFromClassPath(ConfigurationFactory.java:664)
	at org.apache.openejb.config.ConfigurationFactory.getOpenEjbConfiguration(ConfigurationFactory.java:539)
	at org.apache.openejb.config.ConfigurationFactory.getOpenEjbConfiguration(ConfigurationFactory.java:591)
	at org.apache.openejb.assembler.classic.Assembler.getOpenEjbConfiguration(Assembler.java:459)
	at org.apache.openejb.assembler.classic.Assembler.build(Assembler.java:438)
```

How can I use ArchUnit tests and EJB tests in the same .jar?

**Comment by codecholeric** [comment]
I'm not sure if I understand your setup correctly (you didn't specify which OpenEJB version you use, or how your EJB tests look like). I would suggest the problem is an outdated version of ASM within your version of OpenEJB that cannot deal with JDK 9 compiled classes. There is a limited number of those dormant within ArchUnit to ensure compatibility with Java 9 (they are loaded dynamically if the respective Java version is detected at runtime, so normally you don't notice them, but if you scan the whole classpath you'll run into them).
So I would guess you have at least a couple of ways to resolve this

1. upgrade OpenEJB to a version that supports Java 9 :wink: 
2. depending on your test, exclude ArchUnit from being scanned by your OpenEJB implementation (it doesn't make sense anyway to scan those classes), maybe http://tomee.apache.org/properties-listing.html can help?
3. put your EJB integration tests and ArchUnit tests in different modules, so that ArchUnit classes are outside of the classpath of your integration tests
4. just to be complete: Filter the classes that are compiled with target version 1.9 out of the ArchUnit dependency (I wouldn't go this way, since it's brittle, and maybe the repackaged ASM version within ArchUnit will still give you the same problems)

Probably solution 2 would be the way to go for you, if you don't want to split your modules.

**Comment by codecholeric** [comment]
Have you been able to solve your problem?

**Comment by codecholeric** [comment]
I'm closing thing, since I haven't heard back anything and believe it's a configuration error of OpenEJB. If this assumption should be wrong, feel free to reopen this issue!
