### ISSUE TITLE
Support running tests as "JUnit Plugin Test" (in OSGi Environment)

### ISSUE THREAD

**Issue by phermsdorf** [TNG/ArchUnit#346]
Hi,

because of other dependencies i need to start my tests within an OSGi Runtime. When trying to inmport my classes with

`new ClassFileImporter().importPackages("com.godyo")`

i get the following error:

```
com.tngtech.archunit.base.ArchUnitException$UnsupportedUriSchemeException: The scheme of the following URI is not (yet) supported: bundleresource://84.fwk23589725:2/com/godyo/
	at com.tngtech.archunit.core.importer.Location.of(Location.java:171)
	at com.tngtech.archunit.core.importer.Location.of(Location.java:160)
	at com.tngtech.archunit.core.importer.Locations.of(Locations.java:62)
	at com.tngtech.archunit.core.importer.Locations.getResourceLocations(Locations.java:121)
	at com.tngtech.archunit.core.importer.Locations.getLocationsOf(Locations.java:116)
	at com.tngtech.archunit.core.importer.Locations.ofPackage(Locations.java:76)
	at com.tngtech.archunit.core.importer.ClassFileImporter.importPackages(ClassFileImporter.java:207)
	at com.tngtech.archunit.core.importer.ClassFileImporter.importPackages(ClassFileImporter.java:220)
	at com.godyo.p5.dashboard.localization._Messages.testLocalizationNoStatic(_Messages.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:62)
	at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.run(CoreTestApplication.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

```
is there another way of importing the classes to check which works in an OSGi Environment?

Thx.
Bye Peter

**Comment by codecholeric** [comment]
Unfortunately ArchUnit does not support deriving class locations from an OSGI classpath yet.
The way I did it in the past in such environments was to

* define a system property (e.g. `archunit.base.path`) for the base path of your OSGI components
* identify a pattern for the compiled classes you're interested in (e.g. `/target/classes/` or the Eclipse output folder if you're using Eclipse)

Then use something like

```
String basePath = System.getProperty("archunit.base.path");
new ClassFileImporter()
    .withImportOption(location -> location.contains("/target/classes/"))
    .importPath(basePath);
```

If you just want to import a certain package `com.myapp.mydomain.subpackage`, you can instead use the respective `ImportOption`, i.e. 
```
location -> location.contains("/com/myapp/mydomain/subpackage/")
```

It is a little less convenient, but in my experience pretty robust and independent of OSGI specifics.
Does that help you?

**Comment by phermsdorf** [comment]
Thanks for pointing me in the right direction.

I now have a solution that works when executing the tests in Eclipse as Plugin-Test and on the build server where the tests are run using the tycho-surefire plugin:

```
final Bundle bundle = FrameworkUtil.getBundle(getClass());
final URI uri = FileLocator.toFileURL(bundle.getEntry("/")).toURI();

final File classDirectory = new File(uri);
if (!classDirectory.exists()) {
		throw new IllegalStateException("Class Directory not found: " + classDirectory);
}

final JavaClasses importedClasses = new ClassFileImporter().importPath(classDirectory.getAbsolutePath());

```
The difference is that in Eclipse the .class files are extracted whereas in the tycho-surefire build they are packed in .jar files. The FileLocator.toFileURL extracts the contents of the .jar file to a temporary cache directory which then can be used.

FileLocator is part of the org.eclipse.core.runtime bundle so that is somehow Eclipse specific but works for me.

Thanks again and this is a great tool!

Bye Peter

**Comment by codecholeric** [comment]
Happy to hear that it works :smile: 
BTW. you can also import JAR files directly, either by using

```
new ClassFileImporter().importJars(...)
```

or by combining it as locations, if you want to mix and match it with file directories

```
new ClassFileImporter().importLocations(asList(
    Location.of(Paths.get("/some/file/path")), 
    Location.of(new JarFile(new File("/some/jar/file.jar")))));
```

Alternatively you can also use URLs like

```
new ClassFileImporter().importUrls(asList(
    new URL("file:/some/file/path")),
    new URL(new File("jar:file:/some/jar/file.jar!/")));
```
