### ISSUE TITLE
Add support for sealed classes (Java 15 preview feature)

### ISSUE THREAD

**Issue by rweisleder** [TNG/ArchUnit#394]
Java 15 will bring us [JEP 360](https://openjdk.java.net/jeps/360) (preview feature) which introduces sealed classes and permitted subclasses.

Currently, we are using ASM 8.0.1 which already contains _experimental_ support for permitted subtypes. [This merge request for ASM 9](https://gitlab.ow2.org/asm/asm/-/merge_requests/291) contains the official support for this feature.

To do: Which API methods should be added? And should the permitted subclasses be considered as dependencies (if so, in which direction)?

**Comment by rweisleder** [comment]
Sealed classes will be part of Java 17, see [JEP 409](https://openjdk.java.net/jeps/409).

**Comment by stephane-dereppe** [comment]
Hi,

I got this stacktrace when upgrading to java 17:

```
2021-10-30 11:21:24.568  WARN   --- [           main] c.t.a.core.importer.ClassFileProcessor   : Error during import from jrt:/java.base/java/lang/reflect/Executable.class, falling back to simple import

java.lang.UnsupportedOperationException: PermittedSubclasses requires ASM9
	at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassVisitor.visitPermittedSubclass(ClassVisitor.java:266)
	at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.accept(ClassReader.java:683)
	at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at com.tngtech.archunit.core.importer.ClassFileProcessor$UriImporterOfProcessor.tryImport(ClassFileProcessor.java:214)
	at com.tngtech.archunit.core.importer.resolvers.ClassResolverFromClasspath.tryResolve(ClassResolverFromClasspath.java:51)
	at com.tngtech.archunit.core.importer.ImportedClasses.getOrResolve(ImportedClasses.java:57)
	at com.tngtech.archunit.core.importer.ClassGraphCreator.resolveInheritance(ClassGraphCreator.java:137)
	at com.tngtech.archunit.core.importer.ClassGraphCreator.ensureClassesOfInheritanceHierarchiesArePresent(ClassGraphCreator.java:128)
	at com.tngtech.archunit.core.importer.ClassGraphCreator.complete(ClassGraphCreator.java:107)
	at com.tngtech.archunit.core.importer.ClassFileProcessor.process(ClassFileProcessor.java:63)
	at com.tngtech.archunit.core.importer.ClassFileImporter.importLocations(ClassFileImporter.java:336)
	at com.tngtech.archunit.core.importer.ClassFileImporter.importUrls(ClassFileImporter.java:313)
	at com.tngtech.archunit.core.importer.ClassFileImporter.importUrl(ClassFileImporter.java:304)
	at com.tngtech.archunit.junit.ArchUnitTestEngine.getContainedClasses(ArchUnitTestEngine.java:148)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.tngtech.archunit.junit.ArchUnitTestEngine.resolveRequestedClasspathRoot(ArchUnitTestEngine.java:92)
	at com.tngtech.archunit.junit.ArchUnitTestEngine.discover(ArchUnitTestEngine.java:78)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:103)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:85)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:92)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

I think it's related to this issue.

**Comment by commodis** [comment]
Is it possible to add `JavaModifier.SEALED`?

**Comment by szarnekow** [comment]
> Is it possible to add `JavaModifier.SEALED`?

I was wondering the same. Information about sealed classes and permits clauses would be great to have.

**Comment by hankem** [comment]
I'm sorry that this was overlooked for _~~a while~~ years_... 🙈 so thank you for reviving this issue!

About the API: Do you really see a `JavaModifier.SEALED`? I'd rather imagine the following addition to `JavaClass`:
```java
    public Optional<Set<JavaClass>> getPermittedSubclasses() {
        return permittedSubclasses;
    }

    public boolean isSealed() {
        return permittedSubclasses.isPresent();
    }
```

**Comment by commodis** [comment]
My assumption was, that adding the `JavaModifier.SEALED` being an easy way to determine if a class is sealed (like the `abstract` keyword).
I did not check if it reflects the bytecode.

It seems to me, the keyword `sealed` is _not_ within the bytecode:

**Shape.java**
```java
public sealed class Shape permits Circle, Square {
    private final String name;

    public Shape(String name) {
        this.name = name;
    }
}

final class Circle extends Shape {
    public Circle() { super("Circle"); }
}

final class Square extends Shape {
    public Square() { super("Square"); }
}
```

**Compilation**
```batch
javac Shape.java
```

**Shape.class**
```
Classfile /trash/sealed-modifier/Shape.class
  Last modified 27.07.2026; size 325 bytes
  SHA-256 checksum eedf2a9a0e514d5aa1b4a61b4f282c518dd4bbf033789a7486bbeb099144fe4e
  Compiled from "Shape.java"
public class Shape
  minor version: 0
  major version: 69
  flags: (0x0021) ACC_PUBLIC, ACC_SUPER
  this_class: #8                          // Shape
  super_class: #2                         // java/lang/Object
  interfaces: 0, fields: 1, methods: 1, attributes: 2
Constant pool:
   #1 = Methodref          #2.#3          // java/lang/Object."<init>":()V
   #2 = Class              #4             // java/lang/Object
   #3 = NameAndType        #5:#6          // "<init>":()V
   #4 = Utf8               java/lang/Object
   #5 = Utf8               <init>
   #6 = Utf8               ()V
   #7 = Fieldref           #8.#9          // Shape.name:Ljava/lang/String;
   #8 = Class              #10            // Shape
   #9 = NameAndType        #11:#12        // name:Ljava/lang/String;
  #10 = Utf8               Shape
  #11 = Utf8               name
  #12 = Utf8               Ljava/lang/String;
  #13 = Utf8               (Ljava/lang/String;)V
  #14 = Utf8               Code
  #15 = Utf8               LineNumberTable
  #16 = Utf8               SourceFile
  #17 = Utf8               Shape.java
  #18 = Utf8               PermittedSubclasses
  #19 = Class              #20            // Circle
  #20 = Utf8               Circle
  #21 = Class              #22            // Square
  #22 = Utf8               Square
{
  public Shape(java.lang.String);
    descriptor: (Ljava/lang/String;)V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=2, locals=2, args_size=2
         0: aload_0
         1: invokespecial #1                  // Method java/lang/Object."<init>":()V
         4: aload_0
         5: aload_1
         6: putfield      #7                  // Field name:Ljava/lang/String;
         9: return
      LineNumberTable:
        line 4: 0
        line 5: 4
        line 6: 9
}
SourceFile: "Shape.java"
PermittedSubclasses:
  Circle
  Square
```

I guess your suggestion reflects a lot better what the actual bytecode contains.

Here is a suggestion based on your code:
```java
    public Set<JavaClass> getPermittedSubclasses() {
        return permittedSubclasses;
    }

    public boolean isSealed() {
        return !permittedSubclasses.isEmpty();
    }
```

This might be more consistent with the current API like the `JavaClass#getSubclasses()`:

**JavaClass**
```java
public Set<JavaClass> getSubclasses() {
    return subclasses;
}
```

**Comment by hankem** [comment]
There is the corner case that a class file may contain an empty array of `PermittedSubclasses`.
The Java compiler would probably not create such bytecode, but it is technically valid; the reflection API reports:
`EmptyPermittedSubclasses.class.getPermittedSubclasses() == new Class[0] != null`, i.e. `EmptyPermittedSubclasses.class.isSealed() == true`.

That's why I wanted ArchUnit to be able to distinguish 
* `javaClass.getPermittedSubclasses().isEmpty()` vs. 
* `javaClass.getPermittedSubclasses().get().isEmpty()`.

Unfortunately, ASM's `ClassReader` invokes `ClassVisitor#visitPermittedSubclass(String)` for every permitted subclass, so ArchUnit cannot know of empty permitted subclasses from this information. 🙈 But it we ever decide that we want to support that corner case, we can just improve the implementation (using other/additional tools) without having to change `JavaClass`'s API.

What do you think?

**Comment by commodis** [comment]
If the knowledge is important, that the class opted-out of a sealed class, then it should be reflected in the API.

Regarding the method naming: isn't the current convention having `tryGetPermittedSubclasses` in case the return type is `Optional<T>`?

**Comment by hankem** [comment]
Thanks for the discussion, I really appreciate the conversation and shaping the API together! 💙

ArchUnit offers `try`... methods returning `Optional` to answer questions that are justified only in certain conditions:
* `tryGetEnumConstant(String name)` returns empty when the class does not have such an enum constant.
* `tryGetComponentType()` returns empty when the class is not an array.
* `tryGetAnnotationOfType(String typeName)` returns empty when the class does not have such an annotation.
* `tryGetField(String name)` returns empty when the class does not have such a field.
* And simliarly for `tryGetCodeUnitWithParameterTypes`, `tryGetMethod`, `tryGetConstructor`.

But there are also other cases in which the question can always be asked, but the `Optional` result indicates that there might not be a result:
* `Optional<Source> getSource()` – every class could have a source, but it might not be available
* `Optional<JavaType> getSuperclass()`, `Optional<JavaClass> getRawSuperclass()` – every class could have a super class, but not all do.
* `Optional<JavaClass> getEnclosingClass()`, `Optional<JavaCodeUnit> getEnclosingCodeUnit()` – every class could be defined within another class or code unit, but not all are.
* `Optional<JavaStaticInitializer> getStaticInitializer()`  – every class could have a static initializer, not not all do.

So I think there is a subtle difference, and I'd say `getPermittedSubclasses()` is of the second kind: Every class could have it.

Does that make sense to you, @commodis? (If yes, I'd merge the PR #1677 as it is.)

**Comment by commodis** [comment]
Thanks for the explanation! Please merge <3
