### ISSUE TITLE
OutOfMemoryError for method call checks

### ISSUE THREAD

**Issue by slovdahl** [TNG/ArchUnit#399]
I don't know if I'm doing something fundamentally wrong, but I'm getting `OutOfMemoryError` quite often with a test that looks like this:

```java
package foo.bar;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;

import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;

import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import com.tngtech.archunit.core.domain.JavaClasses;
import com.tngtech.archunit.core.importer.ClassFileImporter;
import com.tngtech.archunit.core.importer.ImportOption;

public class ArchitectureTest {

    private JavaClasses classes;

    @BeforeClass
    public void loadClasses() {
        classes = new ClassFileImporter()
                .withImportOption( ImportOption.Predefined.DO_NOT_INCLUDE_TESTS )
                .withImportOption( ImportOption.Predefined.DO_NOT_INCLUDE_ARCHIVES )
                .importPackages( "foo.bar" );
    }

    @Test
    void jdkExecutorsNewFixedThreadPoolNotUsed() {
        noClasses()
                .should().callMethod( Executors.class, "newFixedThreadPool", int.class )
                .orShould().callMethod( Executors.class, "newFixedThreadPool", int.class, ThreadFactory.class )
                .check( classes );
    }
}
```

The `JavaClasses` instance contains about 4500 classes when I see the `OutOfMemoryError`:
```
java.lang.OutOfMemoryError: Java heap space

	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at com.tngtech.archunit.core.domain.JavaAccess.getDescription(JavaAccess.java:125)
	at com.tngtech.archunit.lang.conditions.JavaAccessCondition.check(JavaAccessCondition.java:34)
	at com.tngtech.archunit.lang.conditions.JavaAccessCondition.check(JavaAccessCondition.java:24)
	at com.tngtech.archunit.lang.conditions.ContainAnyCondition.check(ContainAnyCondition.java:40)
	at com.tngtech.archunit.lang.conditions.ContainAnyCondition.check(ContainAnyCondition.java:28)
	at com.tngtech.archunit.lang.conditions.AnyAttributeMatchesCondition.check(AnyAttributeMatchesCondition.java:40)
	at com.tngtech.archunit.lang.conditions.AnyAttributeMatchesCondition.check(AnyAttributeMatchesCondition.java:26)
	at com.tngtech.archunit.lang.ArchCondition$1.check(ArchCondition.java:82)
	at com.tngtech.archunit.lang.ArchCondition$1.check(ArchCondition.java:82)
	at com.tngtech.archunit.lang.ArchCondition$1.check(ArchCondition.java:82)
	at com.tngtech.archunit.lang.ArchCondition$ConditionWithEvents.check(ArchCondition.java:161)
	at com.tngtech.archunit.lang.ArchCondition$ConditionWithEvents.<init>(ArchCondition.java:151)
	at com.tngtech.archunit.lang.ArchCondition$JoinCondition.evaluateConditions(ArchCondition.java:135)
	at com.tngtech.archunit.lang.ArchCondition$OrCondition.check(ArchCondition.java:237)
	at com.tngtech.archunit.lang.conditions.NeverCondition.check(NeverCondition.java:47)
	at com.tngtech.archunit.lang.ArchCondition$1.check(ArchCondition.java:82)
	at com.tngtech.archunit.lang.ArchRule$Factory$SimpleArchRule.evaluate(ArchRule.java:212)
	at com.tngtech.archunit.lang.ArchRule$Assertions.check(ArchRule.java:80)
	at com.tngtech.archunit.lang.ArchRule$Factory$SimpleArchRule.check(ArchRule.java:198)
	at com.tngtech.archunit.lang.syntax.ObjectsShouldInternal.check(ObjectsShouldInternal.java:81)
	at foo.bar.ArchitectureTest.jdkExecutorsNewFixedThreadPoolNotUsed(ArchitectureTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
```

It fails fairly reliably with `-Xmx512m` (which is what Gradle seems to set by default). With e.g. `-Xmx1024m` it works fine.

```
$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
```

Am I doing something wrong? Is it possible to rewrite the rule in a more efficient way?

**Comment by codecholeric** [comment]
Unfortunately ArchUnit is quite hungry for memory. It imports a lot of data into memory, e.g. a textual description of every single dependency from one class to another, which of course grows exponentially. Also if there are a lot of violations, I have experienced building the violation message to fill up the heap.
I can tell that I have tried it with 1GB heap and it worked fine for 13000+ classes, but the same thing failed with 512m. I don't know how your 4500 classes look like, i.e. if they have a lot of dependencies and thus need more heap.
I have also noted that higher JRE versions seem to be more efficient with memory in some experiments.
It would probably be possible to optimize it for lower heap consumption, e.g. building the descriptions lazily only when needed, but it might have a negative impact on performance (which was more what I put focus on so far).
My philosophy so far was, that memory is cheap in 2020 (and only getting cheaper), so I usually went for performance/simplicity when explicitly choosing.
If you can actually import the classes (which seems to be the case if your OOM is during `ArchCondition.check(..)`) and you really want to optimize for low heap, you could try to simply iterate

```
Set<JavaMethodCall> evilCalls = classes.stream()
    .flatMap(JavaClass::getMethodCallsFromSelf)
    .filter(call -> isEvil(call))
    .collect(toSet());
assertThat(evilCalls).isEmpty();
```

and see if that needs less heap. Other than that if you're sure you're not importing too many classes and you need them all, I don't think there is much you can do at the moment, except increase the heap size.

**Comment by slovdahl** [comment]
Thank you for the quick response and the insightful answer, greatly appreciated!

What you say makes sense. And I generally agree with the fact that memory is cheap today. The only reason I'm reluctant to increasing the heap size for JVMs running tests is that we run tests in parallel. In our current setup, this means that Gradle starts as many JVMs as there are cores, and increasing the heap size means that all of those JVM instances will be able to use more memory. But I'll experiment with increasing the heap size anyway :+1: I just realized that another option could be to run the ArchUnit tests in a separate Gradle task. Increasing the heap size for that task would not have the same dramatic effect as doing it for the common test task.

> I have also noted that higher JRE versions seem to be more efficient with memory in some experiments.

Longing for the day when we can go from Java 8 to 11+.. :smile:

Again, thank you for the response, and thank you for an awesome tool! Feel free to close this issue.

**Comment by codecholeric** [comment]
No problem :+1: Yes, in fact I have used that setup often, too, to run the Arch tests in a separate step / task :wink: They can run in parallel to the other test forks then, but with a bigger heap.
