### ISSUE TITLE
Inheritance and Interface checks String vs Class parameter

### ISSUE THREAD

**Issue by nixfuerdiecharts** [TNG/ArchUnit#469]
Frist of all I am an ArchUnit newbie. So I am not shure if this is a real issue or I am misunderstanding the api.

I have implemented a simple Code structure, where a Car class inherits from a Vehicle class. I am trying to test that inheritance with ArchUnit.
When I implement the test with a String parameter, everything works fine, the test goes trough.
```java
@ArchTest
    private final ArchRule vehicle_extentions_should_be_car = classes().that().implement("Vehicle")
            .should().haveSimpleName("Car");
```
But when I pass through the Vehicle as a class, it throws Exceptions
```java
@ArchTest
    private final ArchRule vehicle_extentions_should_be_car = classes().that().implement(Vehicle.class)
            .should().haveSimpleName("Car");
```
```java
java.lang.reflect.InvocationTargetException
com.tngtech.archunit.junit.ArchTestInitializationException: java.lang.reflect.InvocationTargetException
	at com.tngtech.archunit.junit.ArchTestInitializationException$1.apply(ArchTestInitializationException.java:27)
	at com.tngtech.archunit.junit.ArchTestInitializationException$1.apply(ArchTestInitializationException.java:24)
	at com.tngtech.archunit.junit.ReflectionUtils.getValueOrThrowException(ReflectionUtils.java:102)
	at com.tngtech.archunit.junit.ArchTestExecution.getValue(ArchTestExecution.java:53)
	at com.tngtech.archunit.junit.ArchRuleExecution.evaluateOn(ArchRuleExecution.java:39)
	at com.tngtech.archunit.junit.ArchUnitRunner.runChild(ArchUnitRunner.java:154)
	at com.tngtech.archunit.junit.ArchUnitRunner.runChild(ArchUnitRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at com.tngtech.archunit.junit.ArchUnitRunner$1.evaluate(ArchUnitRunner.java:88)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.tngtech.archunit.base.ReflectionUtils.newInstanceOf(ReflectionUtils.java:28)
	at com.tngtech.archunit.junit.ReflectionUtils.newInstanceOf(ReflectionUtils.java:81)
	at com.tngtech.archunit.junit.ReflectionUtils.getValueOrThrowException(ReflectionUtils.java:99)
	... 42 more
Caused by: com.tngtech.archunit.base.ArchUnitException$InvalidSyntaxUsageException: implement(type) can only ever be true, if type is an interface, but type fmg.vehicles.Vehicle is not
	at com.tngtech.archunit.core.domain.JavaClass$Predicates.implement(JavaClass.java:1448)
	at com.tngtech.archunit.lang.syntax.ClassesThatInternal.implement(ClassesThatInternal.java:137)
	at ArchUnitTests.<init>(ArchUnitTests.java:25)
	... 50 more

```

On the other hand, I got a Street class which implements a TrafficSign Interface. In This case the test failes if I pass through a String as a parameter
This test goes through:
```java
@ArchTest
    private final ArchRule street_should_implement_trafficSign = classes().that().resideInAPackage("fmg.streets")
            .and().haveSimpleName("Street")
            .should().implement(TrafficSign.class);
```
This test fails
```java
@ArchTest
    private final ArchRule street_should_implement_trafficSign = classes().that().resideInAPackage("fmg.streets")
            .and().haveSimpleName("Street")
            .should().implement("TrafficSign");
```
```java
Architecture Violation [Priority: MEDIUM] - Rule 'classes that reside in a package 'fmg.streets' and have simple name 'Street' should implement TrafficSign' was violated (1 times):
Class <fmg.streets.Street> does not implement TrafficSign in (Street.java:0)
```

**Comment by hankem** [comment]
Can it be that your String variants don't give the fully qualified class name?
I see a `fmg.vehicles.Vehicle` in the  message of the `ArchUnitException$InvalidSyntaxUsageException`:
```
implement(type) can only ever be true, if type is an interface, but type fmg.vehicles.Vehicle is not
```
If you use `classes().that().implement("Vehicle")` and not `classes().that().implement("fmg.vehicles.Vehicle")`, the test might just _go through_ because there is probably no `Vehicle` class in the default package, and your rule is not selecting any class to test?

<details>
<summary>Side note</summary>

As you're saying _"everything works fine, the test goes trough":_ 
I'd rather say _"everything works fine"_, when a test actually fails when there is a violation. 😉 Did you check that?
(I recommend to really see every test you write fail when the required feature is not functional.)

</details>

Likewise for the second example:
If `TrafficSign.class` was not in the default package, the test `.should().implement("TrafficSign")` would impose a requirement that cannot be fulfilled, hence the test would always fail.

**Comment by codecholeric** [comment]
Also watch out that ArchUnit is very picky about language. The only valid case is a class *implementing* an interface. A class cannot *implement* another class and an interface cannot *implement* another interface. In these cases you need to use the broader *assignable to*.

The reason you have the exception in the one case is actually ArchUnit trying to help you. If you supply a `Class<?>` that is no interface to `implements(..)` then ArchUnit knows you probably made a mistake and didn't realize that a non-interface class can never be "implemented" by another class. Thus it throws the exception. If you pass the string ArchUnit cannot do any validation. Thus your rule will probably never catch anything, no matter the input. As @hankem says, the important thing is to see your rule fail once for the a case where it should. That it is green does not really tell you much, because `noClasses().should().implement("whatever")` will also always pass, but provides little value

**Comment by nixfuerdiecharts** [comment]
Thank you for your help.
@hankem you were right with the fully qualified names. For testing the Interface implementations of a class, i need the fully qualified interface name if I want the parameter to be a string. In this case
``.should().implement("fmg.streets.TrafficSign");`` works as well as 
```java 
import fmg.streets.TrafficSign;
...
.should().implement(TrafficSign.class);
```

@codecholeric Thank you. I was a bit confused when I didn't find something like ``.should().extend("fmg.streets.Car");`` or ``.should().inheritFrom("fmg.streets.Car");``

So would the right Test for inheritance be something like this?
```java
classes().that().haveSimpleName("Car")
            .should().beAssignableTo("fmg.vehicles.Vehicle");
```

**Comment by codecholeric** [comment]
Yes, but I would go for `.should().beAssignableTo(Vehicle.class)` if you can :wink: (refactoring-safe)
The point about `extend(..)` is valid, since there is `implement(..)`, but back then I refrained from adding it, cause the semantics are also somewhat complicated (e.g. a class can extend a class and an interface can extend an interface, but a class can't extend an interface). And I could not think of a case where `assignableTo(..)` would not be good enough for this (and that wording comes from the Java Reflection API).

**Comment by hankem** [comment]
I agree with both of you: ☺
* From the implementation perspective, `beAssignableTo` is what should be used.
* From the user perspective, `extend` is what many (including myself) might at first look for.

Maybe adding
```
@see #beAssignableTo
```
to the [`implement` documentation](https://javadoc.io/doc/com.tngtech.archunit/archunit/0.14.1/com/tngtech/archunit/lang/syntax/elements/ClassesShould.html#implement(java.lang.Class)) would already be helpful?

**Comment by codecholeric** [comment]
In retrospect I'm wondering if it was maybe a mistake to add `implement(..)` at all :joy: Cause that kind of leads you in the wrong direction to expect a `extend(..)` method while otherwise you would maybe immediately look for another solution :thinking:
