### ISSUE TITLE
ASM8

### ISSUE THREAD

**Issue by pawelhulek** [TNG/ArchUnit#564]
Hi 
I just realized that my ArchUnit Tests are not working after upgrade to Java 15. 
I can see the fix for ASM in the source code, but not in version 0.17.0. (or maybe something wrong with my config?)
May I ask when are you planning to release version 0.18.0?

**Comment by rweisleder** [comment]
ArchUnit supports classes compiled with Java 15 since [v0.15.0](https://github.com/TNG/ArchUnit/releases/tag/v0.15.0). The code is tested against Java 15 since v0.17.0 (#438). So there should be no problem per se. 
Have you checked that you use a recent version of ArchUnit?

> my ArchUnit Tests are not working after upgrade to Java 15

Do you get an exception or something like that? What could we do to reproduce your issue?

**Comment by simasch** [comment]
I get java.lang.UnsupportedOperationException: Record requires ASM8 with Java 16.

When will Java 16 be supported?

**Comment by codecholeric** [comment]
Hmm, this is very strange, because as you can see here, https://github.com/TNG/ArchUnit/blob/release-0.16.0/build.gradle#L36 , ArchUnit already uses ASM version `9.0` :thinking: 
I can look into it later. But we can also release in the next days with the newest ASM version and also support for `JavaClass.isRecord()` then.

**Comment by codecholeric** [comment]
@simasch I tried to run [ArchUnit-Examples](https://github.com/TNG/ArchUnit-Examples) both in IntelliJ and with Gradle using JDK 16 and it worked without problems for me. Can you maybe provide a minimal example to reproduce the issue? Are you sure it is ArchUnit that throws this exception? And not the build tool or sth. like that?

**Comment by simasch** [comment]
I will tomorrow. I hope the issue is not IntelliJ related. I had a lot of problems with it lately

**Comment by simasch** [comment]
Unfortunately it's not related to Intellij. This is the full stack trace

```
07:49:41.878 [main] WARN com.tngtech.archunit.core.importer.ClassFileProcessor - Couldn't import class from file:///C:/Users/simon/Workspace/BFH/mio-application/code/application/target/classes/international/mio/order/entity/OrderDTO.class
java.lang.UnsupportedOperationException: Record requires ASM8
        at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassVisitor.visitRecordComponent(ClassVisitor.java:305)
        at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.readRecordComponent(ClassReader.java:930)
        at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.accept(ClassReader.java:708)
        at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at com.tngtech.archunit.core.importer.ClassFileProcessor.process(ClassFileProcessor.java:57)
        at com.tngtech.archunit.core.importer.ClassFileImporter.importLocations(ClassFileImporter.java:336)
        at com.tngtech.archunit.core.importer.ClassFileImporter.importPackages(ClassFileImporter.java:209)
        at com.tngtech.archunit.core.importer.ClassFileImporter.importPackages(ClassFileImporter.java:220)
        at international.mio.ArchitectureTest.<init>(ArchitectureTest.java:33)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.junit.platform.commons.util.ReflectionUtils.newInstance(ReflectionUtils.java:513)
        at org.junit.jupiter.engine.execution.ConstructorInvocation.proceed(ConstructorInvocation.java:56)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:72)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:77)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:342)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:289)
        at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:267)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:259)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:258)
        at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:101)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:100)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:65)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:111)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:111)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:79)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
07:49:41.879 [main] DEBUG com.tngtech.archunit.core.importer.JavaClassProcessor - Analyzing class 'international/mio/customer/entity/Address'
07:49:41.880 [main] DEBUG com.tngtech.archunit.core.importer.JavaClassProcessor - Analyzing class 'org/slf4j/Logger'
07:49:41.881 [main] DEBUG com.tngtech.archunit.core.importer.JavaClassProcessor - Analyzing class 'java/time/LocalDateTime'
07:49:41.882 [main] DEBUG com.tngtech.archunit.core.importer.JavaClassProcessor - Analyzing class 'java/lang/Long'
07:49:41.884 [main] DEBUG com.tngtech.archunit.core.importer.JavaClassProcessor - Analyzing class 'java/util/Set'
07:49:41.885 [main] DEBUG com.tngtech.archunit.core.importer.JavaClassProcessor - Analyzing class 'java/time/LocalDate'
07:49:41.887 [main] DEBUG com.tngtech.archunit.core.importer.JavaClassProcessor - Analyzing class 'java/lang/String'
07:49:41.889 [main] DEBUG com.tngtech.archunit.core.importer.JavaClassProcessor - Analyzing class 'java/lang/Integer'
07:49:41.891 [main] DEBUG com.tngtech.archunit.core.importer.JavaClassProcessor - Analyzing class 'java/math/BigDecimal'
07:49:41.899 [main] DEBUG com.tngtech.archunit.core.importer.JavaClassProcessor - Analyzing class 'java/lang/Object'
07:49:41.900 [main] DEBUG com.tngtech.archunit.core.importer.JavaClassProcessor - Analyzing class 'java/util/Optional'
07:49:41.901 [main] DEBUG com.tngtech.archunit.core.importer.JavaClassProcessor - Analyzing class 'java/util/stream/Stream'
07:49:41.902 [main] DEBUG com.tngtech.archunit.core.importer.JavaClassProcessor - Analyzing class 'international/mio/order/entity/OrderDTO'
07:49:41.903 [main] WARN com.tngtech.archunit.core.importer.ClassFileProcessor - Error during import from file:/C:/Users/simon/Workspace/BFH/mio-application/code/application/target/classes/international/mio/order/entity/OrderDTO.class, falling back to simple import
java.lang.IllegalStateException: Attempted to add java.lang.Record as a second superclass to international.mio.order.entity.OrderDTO, this is most likely a bug
        at com.tngtech.archunit.thirdparty.com.google.common.base.Preconditions.checkState(Preconditions.java:721)
        at com.tngtech.archunit.core.importer.ClassFileImportRecord.setSuperclass(ClassFileImportRecord.java:66)
        at com.tngtech.archunit.core.importer.ClassFileProcessor$ClassDetailsRecorder.onNewClass(ClassFileProcessor.java:83)
        at com.tngtech.archunit.core.importer.JavaClassProcessor.visit(JavaClassProcessor.java:116)
        at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.accept(ClassReader.java:546)
        at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
        at com.tngtech.archunit.core.importer.ClassFileProcessor$UriImporterOfProcessor.tryImport(ClassFileProcessor.java:209)
        at com.tngtech.archunit.core.importer.resolvers.ClassResolverFromClasspath.tryResolve(ClassResolverFromClasspath.java:51)
        at com.tngtech.archunit.core.importer.ImportedClasses.getOrResolve(ImportedClasses.java:57)
        at com.tngtech.archunit.core.importer.ImportedClasses.ensurePresent(ImportedClasses.java:69)
        at com.tngtech.archunit.core.importer.ClassGraphCreator.ensureMemberTypesArePresent(ClassGraphCreator.java:115)
        at com.tngtech.archunit.core.importer.ClassGraphCreator.complete(ClassGraphCreator.java:104)
        at com.tngtech.archunit.core.importer.ClassFileProcessor.process(ClassFileProcessor.java:63)
        at com.tngtech.archunit.core.importer.ClassFileImporter.importLocations(ClassFileImporter.java:336)
        at com.tngtech.archunit.core.importer.ClassFileImporter.importPackages(ClassFileImporter.java:209)
        at com.tngtech.archunit.core.importer.ClassFileImporter.importPackages(ClassFileImporter.java:220)
        at international.mio.ArchitectureTest.<init>(ArchitectureTest.java:33)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.junit.platform.commons.util.ReflectionUtils.newInstance(ReflectionUtils.java:513)
        at org.junit.jupiter.engine.execution.ConstructorInvocation.proceed(ConstructorInvocation.java:56)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
        at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:72)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
        at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:77)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:342)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:289)
        at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:267)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:259)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:258)
        at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:101)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:100)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:65)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:111)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:111)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:79)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

```

**Comment by simasch** [comment]
And here's the project to reproduce the problem:
[](https://github.com/simasch/archunit-java16)

Thanks, Simon

**Comment by rweisleder** [comment]
Looks like v0.17.0 can't analyze records because the API version is set to ASM7: https://github.com/TNG/ArchUnit/blob/937a9cc9d72e6e4baeb6b77594bd14d4abd11963/archunit/src/main/java/com/tngtech/archunit/core/importer/ClassFileProcessor.java#L44

The next release contains #311 where records should be fully supported.

**Comment by hankem** [comment]
[ArchUnit 0.18.0](https://github.com/TNG/ArchUnit/releases/tag/v0.18.0) has just been released.

**Comment by codecholeric** [comment]
Yes, I had overlooked this API constant :disappointed: Lesson learned for the future, don't just upgrade the dependency, also update the API constant... Good thing on master it was already fixed, so I just had to release :+1:

**Comment by codecholeric** [comment]
I would assume with ArchUnit `0.18.0` this issue is solved, if not, feel free to reopen :wink:

**Comment by simasch** [comment]
Works like expected - Thanks a lot!

**Comment by pawelhulek** [comment]
0.18.0 solved the problem. Records are properly handled now! Thanks!
