### ISSUE TITLE
ImmutableSet java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by junsignal** [TNG/ArchUnit#757]
I invoke archunit from androidStudio, but there is an out of memory issue when importing jars, not always, just for some large jars;
I don't know it's the limit of android or the limit of `ImmutableSet`?

1) com.transsion.AppTestMain
```
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
	at com.tngtech.archunit.thirdparty.com.google.common.collect.ImmutableCollection$ArrayBasedBuilder.getReadyToExpandTo(ImmutableCollection.java:463)
	at com.tngtech.archunit.thirdparty.com.google.common.collect.ImmutableCollection$ArrayBasedBuilder.add(ImmutableCollection.java:475)
	at com.tngtech.archunit.thirdparty.com.google.common.collect.ImmutableSet$Builder.add(ImmutableSet.java:457)
	at com.tngtech.archunit.core.importer.ClassFileImportRecord.getMemberSignatureTypeNames(ClassFileImportRecord.java:165)
	at com.tngtech.archunit.core.importer.ClassGraphCreator.ensureMemberTypesArePresent(ClassGraphCreator.java:124)
	at com.tngtech.archunit.core.importer.ClassGraphCreator.complete(ClassGraphCreator.java:114)
	at com.tngtech.archunit.core.importer.ClassFileProcessor.process(ClassFileProcessor.java:64)
	at com.tngtech.archunit.core.importer.ClassFileImporter.importLocations(ClassFileImporter.java:336)
	at com.transsion.AppTestMain.runOnceBeforeClass(AppTestMain.java:72)
	at com.transsion.AppTestMain.beforeClass(AppTestMain.java:35)
```

**Comment by codecholeric** [comment]
That means that the import runs out of memory. So you either need to configure more heap space (pass `-Xmx2G` or something like that as a VM parameter) or you try to limit your imported classes more. I don't know how big your project is, or how you import the classes (are you invoking `importClasspath()` by any chance?).
