### ISSUE TITLE
Package dependency check with enumerations

### ISSUE THREAD

**Issue by paolocarrasco** [TNG/ArchUnit#81]
At the company we work, we want to isolate a package gradually to reach a point where it can be taken to its own JAR. That's why we are we want to avoid this package to access others in the project in the meantime and I want to use ArchUnit to force this, but I have a problem with the enumerations within the package. 

Maybe I'm doing it wrong, or there is a workaround for this. I appreciate any light that takes me in the right path.

I prepared a demo that replicates the behavior here: https://github.com/paolocarrasco/archunit-enumeration-issue.

The body of my test goes something like this:

```java
		noClasses()
			.that()
			.resideInAPackage("package1")
			.should()
			.accessClassesThat()
			.resideOutsideOfPackages(
					"java..",
					"..package1..",
					"..package2..")
			.check(this.javaClasses);
```

After I run the test it shows a message that states something similar to this:
```color:red
java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] - Rule 'no classes that reside in a package 'package1' should access classes that reside outside of packages ['java..', '..package1..', '..package2..']' was violated (1 times):
Method <package1.Colors.values()> calls method <[Lpackage1.Colors;.clone()> in (Colors.java:3)

	at com.tngtech.archunit.lang.ArchRule$Assertions.assertNoViolation(ArchRule.java:92)
	at com.tngtech.archunit.lang.ArchRule$Assertions.check(ArchRule.java:81)
	at com.tngtech.archunit.lang.ArchRule$Factory$SimpleArchRule.check(ArchRule.java:190)
	at com.tngtech.archunit.lang.syntax.ObjectsShouldInternal.check(ObjectsShouldInternal.java:75)
	at com.tngtech.archunit.lang.syntax.ClassesShouldThatInternal.check(ClassesShouldThatInternal.java:366)
	at DependenciesTest.shouldHaveDependenciesOnlyToLowerPackages(DependenciesTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by codecholeric** [comment]
Thanks for providing the full sample to analyze :smiley: 
The effect you experience might seem a little odd, but from the point of view of Java bytecode and the Reflection API (which ArchUnit tries to be consistent with), it's not that surprising.
An Enum like Colors defines a method `Colors.values()` out of the box, and the byte code (`javap -v Colors.class`) shows sth. like

```
#1 = Fieldref           #4.#39         // package1/Colors.$VALUES:[Lpackage1/Colors;
```

and

```
public static package1.Colors[] values();
    ...
    0: getstatic     #1                  // Field $VALUES:[Lpackage1/Colors;
    3: invokevirtual #2                  // Method "[Lpackage1/Colors;".clone:()Ljava/lang/Object;
```

So `Colors.values()` calls `Colors[].clone()` on an array of `Colors`, and if you check the Reflection API, you'll see that

```
System.out.println(Colors.values().getClass().getPackage()); // prints null
```

I.e. classes in the default package and array types have no package, thus ArchUnit uses an empty string there (since ArchUnit never uses null and an empty string seems equivalent in those cases).
Anyway, consequently a method defined in `Colors` (`Colors.values()`) calls a method on an object in the default package, and thus your rule reports

```
Method <package1.Colors.values()> calls method <[Lpackage1.Colors;.clone()> in (Colors.java:3)
```

(if you check `Colors[].class.getName()`, you'll see the weird name `[Lpackage1.Colors;`)
Long story short, if you allow accesses to the default package, you'll ignore those calls

```
noClasses()
		.that()
		.resideInAPackage("package1")
		.should()
		.accessClassesThat()
		.resideOutsideOfPackages(
				"",
				"java..",
				"..package1..",
				"..package2..")
```

Other than that, you could customize this, and explicitly ignore only that call, or only calls to `Array.clone()`, but then you'd have to write more custom code (I could show you, if you're interested, but I'm not sure, if it's really worth it for your case, because classes in the default package are likely not your problem :wink:)

Unfortunately I don't know what ArchUnit could really do to make this more clear, because that is just how the code really is if you look closely, even if it's hidden from the eye during everyday coding.
But I'm open to suggestions!!

**Comment by paolocarrasco** [comment]
Yeah, that workaround helps me, thanks! I don't have any issues with the default package.

Although, I think the dependency from `enum::values()` to `Array::clone()` should be treated differently, as an exception to the rule, otherwise it would allow class members of the package to have dependencies to the default one. Maybe, to have a built-in predicate that use the custom code you have and have something like this:

```
noClasses()
		.that()
		.resideInAPackage("package1")
		.should()
		.accessClassesThat(skippingEnumValues)
		.resideOutsideOfPackages(
				"",
				"java..",
				"..package1..",
				"..package2..")
```

**Comment by codecholeric** [comment]
BTW, there is another way, if you don't want this in your code, you could use an ArchUnit Ignore Pattern, i.e. put `archunit_ignore_patterns.txt` in your `src/test/resources` and add a pattern that matches that specific call, e.g.

```
Method <.*\.values\(\)> calls method <\[L.*\.clone\(\)>.*
```

That should filter all those calls from `.values()` methods to array `clone()` methods. (compare https://www.archunit.org/userguide/html/000_Index.html#_ignoring_violations)
