### ISSUE TITLE
Test case fails for jdk 8 targe compilination but works for jdk 17 default target

### ISSUE THREAD

**Issue by nagkumar** [TNG/ArchUnit#928]
![image](https://user-images.githubusercontent.com/332234/182007196-2221084e-cea1-4e0c-95a9-a1c85e9b9232.png)
![image](https://user-images.githubusercontent.com/332234/182007204-54d2624d-46c0-4252-81fd-1619a6c06f98.png)
![image](https://user-images.githubusercontent.com/332234/182007214-ea31a19e-2d11-4715-a784-e4e7269a30a1.png)

```
java.lang.AssertionError: Architecture Violation [Priority: MEDIUM] - Rule 'Layered architecture consisting of
layer 'Controllers' ('..com.test.controllers..')
layer 'Services' ('..com.test.services..')
layer 'Infrastructure' ('..com.test.infrastructure..')
where layer 'Controllers' may not be accessed by any layer
where layer 'Services' may only be accessed by layers ['Controllers']
where layer 'Infrastructure' may only be accessed by layers ['Services']' was violated (2 times):
Constructor <com.test.infrastructure.FirstRepository.<init>(com.test.services.slice2.SecondService)> has parameter of type <com.test.services.slice2.SecondService> in (FirstRepository.java:0)
Field <com.test.infrastructure.FirstRepository.secondService> has type <com.test.services.slice2.SecondService> in (FirstRepository.java:0)
	at com.tngtech.archunit.lang.ArchRule$Assertions.assertNoViolation(ArchRule.java:91)
	at com.tngtech.archunit.lang.ArchRule$Assertions.check(ArchRule.java:81)
	at com.tngtech.archunit.library.Architectures$LayeredArchitecture.check(Architectures.java:178)
	at LayeredArchitectureTests.layer_dependencies_are_respected(LayeredArchitectureTests.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcce
```

![image](https://user-images.githubusercontent.com/332234/182007228-7994ef38-946a-4a5f-86d2-ad93c049db50.png)

```java
import com.tngtech.archunit.core.domain.JavaClasses;
import com.tngtech.archunit.core.importer.ClassFileImporter;
import com.tngtech.archunit.lang.ArchRule;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

import static com.tngtech.archunit.library.Architectures.layeredArchitecture;

@RunWith(JUnit4.class)
public class LayeredArchitectureTests
{
    @Test
    public void layer_dependencies_are_respected()
    {
	JavaClasses importedClasses = new ClassFileImporter().importPackages("..com.test..");

	ArchRule myRule = layeredArchitecture().layer("Controllers")
					       .definedBy("..com.test.controllers..")
					       .layer("Services")
					       .definedBy("..com.test.services..")
					       .layer("Infrastructure")
					       .definedBy("..com.test.infrastructure..")
					       .whereLayer("Controllers")
					       .mayNotBeAccessedByAnyLayer()
					       .whereLayer("Services")
					       .mayOnlyBeAccessedByLayers("Controllers")
					       .whereLayer("Infrastructure")
					       .mayOnlyBeAccessedByLayers("Services");

	myRule.check(importedClasses);
    }
}
```

**Comment by nagkumar** [comment]
Any reason why this can happen..

**Comment by hankem** [comment]
I don't know why `FirstRepository` violates your `LayeredArchitecture` rule with JDK 8, but not with JDK 17 (if I understood correctly). Could the constructor `FirstRepository(SecondService)` be a synthetic member that might differ when using different compilers? (Could you share the code of `FirstRepository`?)

But anyways: is there a particular reason why you use [ArchUnit 0.10.2](https://github.com/TNG/ArchUnit/releases/tag/v0.10.2) (released more than 3 years ago)? I would recommend to try at least [ArchUnit 0.23.1](https://github.com/TNG/ArchUnit/releases/tag/v0.23.1) if you don't want to make the leap to [ArchUnit 1.0.0-rc1](https://github.com/TNG/ArchUnit/releases/tag/v1.0.0-rc1) already. If your issue is still there, it seems worth investigating!

**Comment by nagkumar** [comment]
I am referring to this code..

https://github.com/mstrYoda/java-archunit-examples, I have locally copied and changed the build script file as this..

`package com.test.infrastructure;

import com.test.Repository;
import com.test.services.slice2.SecondService;

@Repository
public final class FirstRepository
{
    SecondService secondService;

    public FirstRepository(SecondService secondService)
    {
	this.secondService = secondService;
    }
}
`

My build script is

`import java.awt.Desktop

plugins {
    java
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("com.tngtech.archunit:archunit-junit4:0.10.2")
}

group = "groupId"
version = "1.0-SNAPSHOT"
description = "Yoda"
//java.sourceCompatibility = JavaVersion.VERSION_1_8

tasks.withType<Test> {
    ignoreFailures = true
}

tasks.register("openTR") {
    doLast {
	Desktop.getDesktop().browse(File("$buildDir/reports/tests/test/index.html").toURI())
    }
}

defaultTasks("clean", "test", "openTR")

`

**Comment by nagkumar** [comment]
Even with 0.23.1 issue remains the same..

![image](https://user-images.githubusercontent.com/332234/182060571-be988691-8bae-4b94-9f41-257cac750468.png)

**Comment by nagkumar** [comment]
On the version 1.0.0-rc1 also it fails both on jdk 8 and jdk17 with the same error..with target being 8 or target being default that comes with jdk

![image](https://user-images.githubusercontent.com/332234/182066109-1c772fd2-4069-4e7e-b155-ba4a16a25dc5.png)

**Comment by codecholeric** [comment]
I think the reason is that ArchUnit 0.10.2 is quite "ancient" :wink: ArchUnit uses the ASM library under the hood to parse bytecode and ArchUnit 0.10.2 wasn't capable of understanding target level 17 for sure.
ArchUnit 0.10.2 was released Mar 2019 while JDK 17 reached GA in 2021. So I would suspect that you can find quite many error log statements that will tell you that the bytecode of those classes can't be parsed.

**Comment by codecholeric** [comment]
Is there anything more we can do for this issue? To me it feels understood now and the problem should not occur anymore with current versions, right?
